language: python
python: 3.5

install:
  - pip3 install pytest-cov pycodestyle codecov

script:
  - pip3 install -r requirements.txt
  - ./scripts/run-dependencies.sh
  - pytest --cov=src
  - pycodestyle .

after_script:
  - ./scripts/clear-docker.sh

after_success:
  - codecov

services:
  - docker